#!/usr/bin/env node
/**
 * /slop-setup — scaffolds the configuration and registers the status line.
 *
 * Two strict rules:
 *   1. No existing file is ever overwritten. Being safe to re-run after every
 *      update depends on that rule.
 *   2. settings.json is backed up before it is touched, and if the user already
 *      has a statusLine entry it is left alone — overwriting it would quietly
 *      take over their configuration.
 */

import { writeFileSync, readFileSync, existsSync, mkdirSync, copyFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { DEFAULT_CONFIG, paths, readJsonFile } from '../lib/config.mjs';
import { BRAND } from '../lib/report.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SETTINGS = join(homedir(), '.claude', 'settings.json');
const LAUNCHER = join(paths.dir, 'statusline-launcher.mjs');
const STATUSLINE_CMD = `node "${LAUNCHER}"`;

const out = [];
const done = (t) => out.push(`  + ${t}`);
const kept = (t) => out.push(`  = ${t}`);
const warn = (t) => out.push(`  ! ${t}`);

/** Writes only when absent. Returns whether it wrote. */
function writeIfAbsent(file, content, label) {
  if (existsSync(file)) { kept(`${label} already exists, left alone`); return false; }
  try {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
    done(`${label} created: ${file}`);
    return true;
  } catch (error) {
    warn(`${label} could not be written — ${error.message}`);
    return false;
  }
}

out.push(`${BRAND} setup`, '');

// 1. Configuration files — the defaults derive from code, never hand-written.
const defaults = {
  enabled: DEFAULT_CONFIG.enabled,
  mode: DEFAULT_CONFIG.mode,
  disabled: [],
  trustedPackages: [],
  allowTestWrites: DEFAULT_CONFIG.allowTestWrites,
  thresholds: { ...DEFAULT_CONFIG.thresholds },
  ui: { ...DEFAULT_CONFIG.ui },
};
writeIfAbsent(paths.config, JSON.stringify(defaults, null, 2) + '\n', 'config.json');

writeIfAbsent(paths.localPatterns, JSON.stringify({
  patterns: [
    {
      key: 'example-urgent-todo',
      id: 'CODE-03',
      scope: 'code',
      severity: 'warn',
      // String.raw: this pattern passes through three escaping layers on its way
      // from JS to JSON to RegExp. Hand-counted backslashes break silently there;
      // a raw string makes that class of mistake impossible.
      match: String.raw`TODO\s*\(urgent\)`,
      flags: 'gi',
      detects: 'A TODO marked urgent with no owner and no date.',
      fix: 'Either do it now, or open an issue and reference its number.',
    },
  ],
}, null, 2) + '\n', 'patterns.local.json (example)');

const rulesTemplate = join(ROOT, 'templates', 'rules.local.md');
if (existsSync(rulesTemplate)) {
  if (existsSync(paths.localRules)) kept('rules.local.md already exists, left alone');
  else {
    try {
      mkdirSync(dirname(paths.localRules), { recursive: true });
      copyFileSync(rulesTemplate, paths.localRules);
      done(`rules.local.md created: ${paths.localRules}`);
    } catch (error) {
      warn(`rules.local.md could not be written — ${error.message}`);
    }
  }
} else {
  warn('the rules.local.md template was not found');
}

// 2. The status line launcher.
//
// settings.json points at a fixed path in the configuration directory, and the
// launcher forwards to the installed plugin. Without this indirection the entry
// would carry a versioned cache path and every update would break the bar —
// which is exactly the kind of silent failure this project exists to prevent.
const launcherBody = `#!/usr/bin/env node
// Generated by LenaRise.SlopGuard /slop-setup. Do not edit.
//
// settings.json points here rather than at the versioned plugin cache path, so
// an update cannot break the status line. This file resolves the newest
// installed version at run time.
import { readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { homedir } from 'node:os';

const roots = [
  join(homedir(), '.claude', 'plugins', 'cache', 'lenarise-slopguard', 'lenarise-slopguard'),
  join(homedir(), '.claude', 'skills', 'lenarise-slopguard'),
];

function newest() {
  for (const root of roots) {
    if (!existsSync(root)) continue;
    let entries;
    try {
      entries = readdirSync(root).filter((name) => existsSync(join(root, name, 'bin', 'statusline.mjs')));
    } catch (error) {
      process.stderr.write(\`LenaRise.SlopGuard [launcher] \${root} could not be read — \${error.message}\\n\`);
      continue;
    }
    if (entries.length === 0) {
      if (existsSync(join(root, 'bin', 'statusline.mjs'))) return root;
      continue;
    }
    entries.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
    return join(root, entries[entries.length - 1]);
  }
  return null;
}

const base = newest();
if (!base) {
  process.stdout.write('SlopGuard not installed');
  process.exit(0);
}
await import(join(base, 'bin', 'statusline.mjs'));
`;

try {
  mkdirSync(paths.dir, { recursive: true });
  const current = existsSync(LAUNCHER) ? readFileSync(LAUNCHER, 'utf8') : null;
  if (current === launcherBody) kept('statusline-launcher.mjs is current');
  else { writeFileSync(LAUNCHER, launcherBody); done(`statusline-launcher.mjs ${current ? 'refreshed' : 'created'}`); }
} catch (error) {
  warn(`statusline-launcher.mjs could not be written — ${error.message}`);
}

const settings = readJsonFile(SETTINGS);
if (!settings.ok) {
  warn(`settings.json could not be read (${settings.error}); statusLine was not registered`);
  warn('Fix the file, then run /slop-setup again.');
} else {
  const current = settings.value ?? {};
  const existing = current.statusLine?.command ?? '';
  // Case-insensitive: the real path can be spelled "LenaRise.SlopGuard", and a
  // case-sensitive comparison mistook our own entry for a stranger's.
  const mark = existing.toLowerCase();
  const isOurs = mark.includes('statusline') && mark.includes('slopguard');

  if (isOurs && existing === STATUSLINE_CMD) {
    kept('statusLine is current');
  } else if (existing && !isOurs) {
    // Someone else's entry: left alone. Overwriting it would quietly take over
    // the user's configuration.
    warn('statusLine points at a different command, left alone:');
    warn(`  ${existing}`);
    warn('To use ours, replace it with:');
    warn(`  ${STATUSLINE_CMD}`);
  } else {
    // Either empty, or an older entry of ours. An older entry must be migrated:
    // early versions wrote a versioned cache path, and that path goes stale on
    // every update.
    try {
      if (existsSync(SETTINGS)) {
        copyFileSync(SETTINGS, `${SETTINGS}.slopguard-backup`);
        done(`settings.json backed up: ${SETTINGS}.slopguard-backup`);
      }
      mkdirSync(dirname(SETTINGS), { recursive: true });
      current.statusLine = { type: 'command', command: STATUSLINE_CMD };
      writeFileSync(SETTINGS, JSON.stringify(current, null, 2) + '\n');
      done(isOurs ? 'statusLine moved to the version-independent launcher' : 'statusLine registered');
    } catch (error) {
      warn(`settings.json could not be written — ${error.message}`);
    }
  }
}

// 3. The liveness rule — protection against a silent death.
//
// It is installed automatically because this rule is the ONLY layer that runs
// when the plugin is dead: if hooks are not registered, the hook that would ask
// "are you running?" is not there either. On top of that the status line is not
// visible everywhere (the desktop app's Code tab does not render statusLine —
// measured), so for some users no other mechanism would catch a silent death.
//
// It is safe because of the markers: only our own block is written, the rest of
// the file is untouched, and deleting the block removes it cleanly.
// --skip-claude-md opts out.
out.push('');
const claudeMd = join(homedir(), '.claude', 'CLAUDE.md');
const START = '<!-- LenaRise.SlopGuard: liveness rule — start -->';
const END = '<!-- LenaRise.SlopGuard: liveness rule — end -->';

if (process.argv.includes('--skip-claude-md')) {
  kept('liveness rule skipped (--skip-claude-md)');
} else {
  const snippetFile = join(ROOT, 'templates', 'claude-md-snippet.md');
  let snippet = null;
  try {
    snippet = readFileSync(snippetFile, 'utf8').trim();
  } catch (error) {
    warn(`the liveness rule template could not be read — ${error.message}`);
  }

  if (snippet) {
    try {
      const existing = existsSync(claudeMd) ? readFileSync(claudeMd, 'utf8') : null;
      const start = existing?.indexOf(START) ?? -1;
      const end = existing?.indexOf(END) ?? -1;

      if (existing !== null && start !== -1 && end !== -1) {
        const currentBlock = existing.slice(start, end + END.length);
        if (currentBlock === snippet) {
          kept('~/.claude/CLAUDE.md liveness rule is current');
        } else {
          copyFileSync(claudeMd, `${claudeMd}.slopguard-backup`);
          writeFileSync(claudeMd, existing.slice(0, start) + snippet + existing.slice(end + END.length));
          done('~/.claude/CLAUDE.md liveness rule refreshed (only the marked block)');
        }
      } else {
        mkdirSync(dirname(claudeMd), { recursive: true });
        if (existing !== null) {
          copyFileSync(claudeMd, `${claudeMd}.slopguard-backup`);
          writeFileSync(claudeMd, `${existing.trimEnd()}\n\n${snippet}\n`);
          done('~/.claude/CLAUDE.md liveness rule appended');
        } else {
          writeFileSync(claudeMd, `${snippet}\n`);
          done('~/.claude/CLAUDE.md created with the liveness rule');
        }
        out.push('     To remove it, delete the block between the two markers; the rest is yours.');
      }
    } catch (error) {
      warn(`~/.claude/CLAUDE.md could not be written — ${error.message}`);
      warn(`To add it by hand: ${snippetFile}`);
    }
  }
}

out.push('');
out.push('  Claude Code must be restarted for hook changes to apply.');
out.push('  To verify the installation: /slop-doctor');

process.stdout.write(out.join('\n') + '\n');
